site_name: BCILITY DOCS
plugins:
  - search
  - i18n:
    docs_structure: folder
    fallback_to_default: true
    languages:
      - build: true
        default: true
        locale: en
        name: English
      - build: true
        locale: sr
        name: Srpski
theme:
  name: material
  logo: /assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: white
      accent: teal
      toggle:
        icon: material/lightbulb 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
extra_css:
  - overrides/extra.css     
extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Srpski
      link: /sr/
      lang: sr
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/solid/house
      link: https://bcility.com/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/bcility/
    - icon: fontawesome/brands/linkedin
      link: https://rs.linkedin.com/company/bcility

        

copyright: |
  &copy; 2025 <a href="https://bcility.com/"  target="_blank" rel="noopener">BCILITY</a>
