site_name: BCILITY DOCS
plugins:
  - search
  - i18n:
      docs_structure: folder
      fallback_to_default: false
      default language: sh
      languages:
        - locale: en
          name: English
          build: true
          docs_dir: docs/en  # Engleski fajlovi se učitavaju iz `docs/en`
        - locale: sh
          name: Srpski
          default: true
          build: true
          docs_dir: docs/sh  # Srpski fajlovi se učitavaju iz `docs/sh`

theme:
  name: material
  custom_dir: overrides
  logo: /assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.footer
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: white
      accent: teal
      toggle:
        icon: material/lightbulb 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
extra_css:
  - overrides/extra.css  
 
extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Srpski
      link: /sh/
      lang: sh
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/solid/house
      link: https://bcility.com/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/bcility/
    - icon: fontawesome/brands/linkedin
      link: https://rs.linkedin.com/company/bcility

use_directory_urls: false

copyright: |
  &copy; 2025 <a href="https://bcility.com/"  target="_blank" rel="noopener">BCILITY</a>
