site_name: BCILITY DOCS
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: sr
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/solid/house
      link: https://bcility.com/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/bcility/
    - icon: fontawesome/brands/linkedin
      link: https://rs.linkedin.com/company/bcility
  
copyright: |
  &copy; 2025 <a href="https://bcility.com/"  target="_blank" rel="noopener">BCILITY</a>
